### ISSUE TITLE
Question: How Isomorphic Works

### ISSUE THREAD

**Issue by stephencweiss** [kkomelin/isomorphic-dompurify#10] opened 2020-07-07 20:43 UTC
Let me start by saying: thank you so much for this library! I just used it and it works like a charm with my NextJS implementation. I just don't understand _why_ (and that hurts 😄 ), so, I admit this is mostly just my lack of understanding around _how_ this is working, but if you'll entertain me...

Am I right in the following understanding of how this library works:

1. `function r(m){return m && m.default || m;}` returns the default export if available, else just whatever `m` is (i.e. a module)
2. We export `global.DOMPurify` _if_ it exists (meaning `global` exists, meaning we're in `node`)... or
3. `typeof process === undefined` meaning we're _not_ in `node` (is this not redundant?) and so we can return just `dompurify` since we don't need `jsdom` on the client-side, else
4. we _are_ in `node`, so we need to use `JSDOM` to initialize a virtual(?) DOM with JS for `DOMPurify` server-side?

```
function r(m){return m && m.default || m;}
module.exports = global.DOMPurify = global.DOMPurify || (
	typeof process === 'undefined' ? r(require('dompurify')) : (function() {
    const DOMPurifyInitializer = r(require('dompurify'));
    const { JSDOM } = r(require('jsdom'));
    const { window } = new JSDOM('<!DOCTYPE html>');
    return DOMPurifyInitializer(window);
	})()
);
```

For reference, here's me confirming that `process` would be defined in `node`

```shell
$ node
Welcome to Node.js v12.16.2.
Type ".help" for more information.
> typeof process
'object'
```

**Comment by kkomelin** [comment] 2020-07-07 21:15
@stephencweiss Thanks for your kind words and the question.

Let's start from not using "virtual DOM" term in this context because it can be confused with the virtual DOM which is [used in React](https://reactjs.org/docs/faq-internals.html) and other modern frontend frameworks. As I understand, JSDOM has a different purpose and implementation.

To be honest, I didn't change much in the skeleton code which is [provided by the Isomorphic Unfetch](https://github.com/developit/unfetch/blob/master/packages/isomorphic-unfetch/index.js) because it worked for me well enough and I didn't find anything suspicious in it at that time.

But I'm open to improve the code, so please give me some time to check my assumptions to provide a more detailed answer.

**Comment by kkomelin** [comment] 2020-07-08 06:01
First, let's ignore `r(m)` function because its purpose is more or less clear and it doesn't add any significant complexity.

I can't give you 100% answers but can share my considerations...

1) In the Node environment, this piece of code `module.exports = global.DOMPurify = [some code]` allows us both:
```javascript
const DOMPurify = require('isomorphic-dompurify');
DOMPurify.sanitize('<iframe>Iframe!</iframe>');
```
and 
```javascript
require('isomorphic-dompurify');
DOMPurify.sanitize('<iframe>Iframe!</iframe>');
```
2) My guess is that `module.exports = global.DOMPurify = global.DOMPurify || [init logic]` was aimed as a caching mechanism (sort of a singleton), so that if you would import the module twice, it would execute the init logic only once:
```javascript
require('isomorphic-dompurify');
require('isomorphic-dompurify');
```
but modern versions of Node cache multiple imports of the same module anyway, so it can be redundant.

3) I was thinking about why we have both conditions for checking whether it's Node: `global.DOMPurify` and `typeof process === 'undefined'`. But then I confirmed that `<script type="module"` doesn't have `global` object defined, so the `global` object only exists inside a Node script.

4) I still need to check what Webpack produces when configured to compile to es5.

The Isomorphic Unfetch was created quite a while ago and it could be targeted to previous versions of Node and browsers. I guess they tried to predict all possible use cases, such as Webpack, SSR, without SSR, different browsers, different browser versions. And as I already mentioned, I just reused the approach that worked fine for me on other projects. 

It's great that there are people who question solutions - that's a rare skill. But if we have some risk to break what's already working well, it'd be great to have it tested in all possible environments. But who can guarantee we tested it everywhere?

**Comment by stephencweiss** [comment] 2020-07-08 16:13
@kkomelin Thanks for diving in!

Is it fair to say that my summary was accurate then? The biggest piece I was missing was some of the context around `isomorphic-fetch` and the support for older versions of `node` / browsers?

I don't think we need to change the code - as you noted, this works and a re-write will likely introduce bugs that the `isomorphic-fetch` folks already experienced and squashed. 

I just like understanding how things work (and, not a formally trained computer scientist, some terms like `isomorphic` can be confusing to me 😄 ).

Cheers!

**Comment by kkomelin** [comment] 2020-07-09 06:35
@stephencweiss Yes, I think your summary of the module logic was quite accurate. Thanks again for asking this question. Good one.
It seems like we can close the issue for now but feel free to create new ones when necessary.

**Closed by kkomelin** 2020-07-09 06:35 UTC
